//! Checked dispatch for the entrypoints generated by [`crate::pam_module!`].

use crate::{Pam, PamError, PamFlags};
use std::ffi::{c_void, CStr};
use std::os::raw::{c_char, c_int};
use std::ptr::NonNull;

const MAX_MODULE_ARGS: usize = 256;

/// Validate a raw PAM callback invocation and dispatch it to a Rust hook.
///
/// This function is public only so the exported [`crate::pam_module!`] macro
/// can call it from a downstream crate.
///
/// # Safety
///
/// - `pamh` must be a valid PAM handle for the duration of `hook` when non-null.
/// - When `argc > 0`, `argv` must point to an array of `argc` pointers.
/// - Every non-null argument pointer must name a terminated C string that
///   remains valid for the duration of this call.
#[doc(hidden)]
pub unsafe fn invoke_hook<F>(
    pamh: *mut c_void,
    flags: c_int,
    argc: c_int,
    argv: *const *const c_char,
    hook: F,
) -> c_int
where
    F: FnOnce(Pam, PamFlags, Vec<String>) -> PamError,
{
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let handle = match NonNull::new(pamh) {
            Some(handle) => handle,
            None => return PamError::ABORT as c_int,
        };
        if argc < 0 {
            return PamError::ABORT as c_int;
        }
        // argc is non-negative and capped below, so it fits usize on every
        // supported Linux target.
        let count = argc as usize;
        if count > MAX_MODULE_ARGS || (count > 0 && argv.is_null()) {
            return PamError::ABORT as c_int;
        }
        let raw_args: &[*const c_char] = if count == 0 {
            &[]
        } else {
            // SAFETY: the caller guarantees an array of `argc` pointers; the
            // checks above reject negative, oversized, and null-array cases.
            unsafe { std::slice::from_raw_parts(argv, count) }
        };
        let mut args = Vec::with_capacity(count);
        for raw in raw_args {
            if (*raw).is_null() {
                return PamError::ABORT as c_int;
            }
            // SAFETY: the caller guarantees every non-null entry points to a
            // terminated C string valid for this call.
            let arg = unsafe { CStr::from_ptr(*raw) };
            match arg.to_str() {
                Ok(arg) => args.push(arg.to_owned()),
                Err(_) => return PamError::SERVICE_ERR as c_int,
            }
        }
        hook(
            Pam::from_non_null(handle),
            PamFlags::from_bits_truncate(flags),
            args,
        ) as c_int
    }));
    match result {
        Ok(result) => result,
        Err(payload) => {
            // A hostile panic payload may itself panic while being dropped.
            // Contain that second panic too; leaking its payload is preferable
            // to unwinding across the PAM C ABI.
            if let Err(nested_payload) =
                std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| drop(payload)))
            {
                std::mem::forget(nested_payload);
            }
            PamError::ABORT as c_int
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::PamError;
    use std::ffi::{c_void, CString};
    use std::os::raw::{c_char, c_int};
    use std::ptr;

    fn valid_handle() -> *mut c_void {
        ptr::NonNull::<u8>::dangling().as_ptr() as *mut c_void
    }

    fn call(pamh: *mut c_void, argc: c_int, argv: *const *const c_char) -> c_int {
        // SAFETY: each test either supplies a case that must be rejected before
        // dereference or owns every C string and pointer array for the call.
        unsafe { invoke_hook(pamh, 0, argc, argv, |_pam, _flags, _args| PamError::SUCCESS) }
    }

    #[test]
    fn null_handle_aborts_before_the_hook() {
        assert_eq!(
            call(ptr::null_mut(), 0, ptr::null()),
            PamError::ABORT as c_int
        );
    }

    #[test]
    fn negative_argc_aborts_before_pointer_use() {
        assert_eq!(
            call(valid_handle(), -1, ptr::null()),
            PamError::ABORT as c_int
        );
    }

    #[test]
    fn positive_argc_with_null_argv_aborts() {
        assert_eq!(
            call(valid_handle(), 1, ptr::null()),
            PamError::ABORT as c_int
        );
    }

    #[test]
    fn null_argv_element_aborts() {
        let argv = [ptr::null()];
        assert_eq!(
            call(valid_handle(), 1, argv.as_ptr()),
            PamError::ABORT as c_int
        );
    }

    #[test]
    fn oversized_argc_aborts_before_reading_the_array() {
        let argv = [ptr::null()];
        assert_eq!(
            call(valid_handle(), 257, argv.as_ptr()),
            PamError::ABORT as c_int
        );
    }

    #[test]
    fn invalid_utf8_is_a_service_error() {
        let invalid = CString::new(vec![0xff]).expect("no interior null");
        let argv = [invalid.as_ptr()];
        assert_eq!(
            call(valid_handle(), 1, argv.as_ptr()),
            PamError::SERVICE_ERR as c_int
        );
    }

    #[test]
    fn hook_panic_becomes_abort() {
        // SAFETY: the non-null handle is opaque and the hook never dereferences
        // it; zero arguments require no argv allocation.
        let result = unsafe {
            invoke_hook(valid_handle(), 0, 0, ptr::null(), |_pam, _flags, _args| {
                panic!("intentional hook panic")
            })
        };
        assert_eq!(result, PamError::ABORT as c_int);
    }

    #[test]
    fn panicking_payload_drop_is_contained() {
        struct PanicsOnDrop;

        impl Drop for PanicsOnDrop {
            fn drop(&mut self) {
                panic!("intentional payload-drop panic");
            }
        }

        // SAFETY: the non-null handle is opaque and the hook never dereferences
        // it; zero arguments require no argv allocation.
        let result = unsafe {
            invoke_hook(valid_handle(), 0, 0, ptr::null(), |_pam, _flags, _args| {
                std::panic::resume_unwind(Box::new(PanicsOnDrop))
            })
        };
        assert_eq!(result, PamError::ABORT as c_int);
    }

    #[test]
    fn valid_arguments_reach_the_hook_in_order() {
        let first = CString::new("mode=auth").expect("literal has no null");
        let second = CString::new("debug").expect("literal has no null");
        let argv = [first.as_ptr(), second.as_ptr()];

        // SAFETY: the opaque handle is non-null, and both C strings and the
        // pointer array remain valid for the duration of the call.
        let result = unsafe {
            invoke_hook(valid_handle(), 0, 2, argv.as_ptr(), |_pam, flags, args| {
                assert!(flags.is_empty());
                assert_eq!(args, ["mode=auth", "debug"]);
                PamError::SUCCESS
            })
        };
        assert_eq!(result, PamError::SUCCESS as c_int);
    }
}
